/**
 * generated by Xtext 2.13.0
 */
package org.xtext.hlcl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Dom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.hlcl.BoolDom#getDom <em>Dom</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.hlcl.HlclPackage#getBoolDom()
 * @model
 * @generated
 */
public interface BoolDom extends Dom
{
  /**
   * Returns the value of the '<em><b>Dom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dom</em>' attribute.
   * @see #setDom(String)
   * @see org.xtext.hlcl.HlclPackage#getBoolDom_Dom()
   * @model
   * @generated
   */
  String getDom();

  /**
   * Sets the value of the '{@link org.xtext.hlcl.BoolDom#getDom <em>Dom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dom</em>' attribute.
   * @see #getDom()
   * @generated
   */
  void setDom(String value);

} // BoolDom
