/**
 * generated by Xtext 2.13.0
 */
package org.xtext.hlcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.hlcl.HlclPackage#getDom()
 * @model
 * @generated
 */
public interface Dom extends EObject
{
} // Dom
