/**
 * generated by Xtext 2.13.0
 */
package org.xtext.hlcl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.hlcl.HlclFactory
 * @model kind="package"
 * @generated
 */
public interface HlclPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hlcl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/Hlcl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hlcl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HlclPackage eINSTANCE = org.xtext.hlcl.impl.HlclPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.ConstraintProgramImpl <em>Constraint Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.ConstraintProgramImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getConstraintProgram()
   * @generated
   */
  int CONSTRAINT_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_PROGRAM__VARS = 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_PROGRAM__CONSTRAINTS = 1;

  /**
   * The number of structural features of the '<em>Constraint Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.VariablesImpl <em>Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.VariablesImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getVariables()
   * @generated
   */
  int VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__NAME = 0;

  /**
   * The feature id for the '<em><b>Dom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__DOM = 1;

  /**
   * The number of structural features of the '<em>Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.DomImpl <em>Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.DomImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getDom()
   * @generated
   */
  int DOM = 2;

  /**
   * The number of structural features of the '<em>Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.RangeDomImpl <em>Range Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.RangeDomImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getRangeDom()
   * @generated
   */
  int RANGE_DOM = 3;

  /**
   * The feature id for the '<em><b>Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_DOM__START = DOM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_DOM__END = DOM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Range Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_DOM_FEATURE_COUNT = DOM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.SetDomImpl <em>Set Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.SetDomImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getSetDom()
   * @generated
   */
  int SET_DOM = 4;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_DOM__LIST = DOM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Set Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SET_DOM_FEATURE_COUNT = DOM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.BoolDomImpl <em>Bool Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.BoolDomImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getBoolDom()
   * @generated
   */
  int BOOL_DOM = 5;

  /**
   * The feature id for the '<em><b>Dom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_DOM__DOM = DOM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_DOM_FEATURE_COUNT = DOM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.hlcl.impl.StringDomImpl <em>String Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.hlcl.impl.StringDomImpl
   * @see org.xtext.hlcl.impl.HlclPackageImpl#getStringDom()
   * @generated
   */
  int STRING_DOM = 6;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DOM__LIST = DOM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DOM_FEATURE_COUNT = DOM_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.ConstraintProgram <em>Constraint Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint Program</em>'.
   * @see org.xtext.hlcl.ConstraintProgram
   * @generated
   */
  EClass getConstraintProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.hlcl.ConstraintProgram#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.xtext.hlcl.ConstraintProgram#getVars()
   * @see #getConstraintProgram()
   * @generated
   */
  EReference getConstraintProgram_Vars();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.hlcl.ConstraintProgram#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Constraints</em>'.
   * @see org.xtext.hlcl.ConstraintProgram#getConstraints()
   * @see #getConstraintProgram()
   * @generated
   */
  EAttribute getConstraintProgram_Constraints();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.Variables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variables</em>'.
   * @see org.xtext.hlcl.Variables
   * @generated
   */
  EClass getVariables();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.hlcl.Variables#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.hlcl.Variables#getName()
   * @see #getVariables()
   * @generated
   */
  EAttribute getVariables_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.hlcl.Variables#getDom <em>Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dom</em>'.
   * @see org.xtext.hlcl.Variables#getDom()
   * @see #getVariables()
   * @generated
   */
  EReference getVariables_Dom();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.Dom <em>Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dom</em>'.
   * @see org.xtext.hlcl.Dom
   * @generated
   */
  EClass getDom();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.RangeDom <em>Range Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range Dom</em>'.
   * @see org.xtext.hlcl.RangeDom
   * @generated
   */
  EClass getRangeDom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.hlcl.RangeDom#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Start</em>'.
   * @see org.xtext.hlcl.RangeDom#getStart()
   * @see #getRangeDom()
   * @generated
   */
  EAttribute getRangeDom_Start();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.hlcl.RangeDom#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.hlcl.RangeDom#getEnd()
   * @see #getRangeDom()
   * @generated
   */
  EAttribute getRangeDom_End();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.SetDom <em>Set Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Set Dom</em>'.
   * @see org.xtext.hlcl.SetDom
   * @generated
   */
  EClass getSetDom();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.hlcl.SetDom#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.hlcl.SetDom#getList()
   * @see #getSetDom()
   * @generated
   */
  EAttribute getSetDom_List();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.BoolDom <em>Bool Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Dom</em>'.
   * @see org.xtext.hlcl.BoolDom
   * @generated
   */
  EClass getBoolDom();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.hlcl.BoolDom#getDom <em>Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dom</em>'.
   * @see org.xtext.hlcl.BoolDom#getDom()
   * @see #getBoolDom()
   * @generated
   */
  EAttribute getBoolDom_Dom();

  /**
   * Returns the meta object for class '{@link org.xtext.hlcl.StringDom <em>String Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Dom</em>'.
   * @see org.xtext.hlcl.StringDom
   * @generated
   */
  EClass getStringDom();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.hlcl.StringDom#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>List</em>'.
   * @see org.xtext.hlcl.StringDom#getList()
   * @see #getStringDom()
   * @generated
   */
  EAttribute getStringDom_List();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HlclFactory getHlclFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.ConstraintProgramImpl <em>Constraint Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.ConstraintProgramImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getConstraintProgram()
     * @generated
     */
    EClass CONSTRAINT_PROGRAM = eINSTANCE.getConstraintProgram();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT_PROGRAM__VARS = eINSTANCE.getConstraintProgram_Vars();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTRAINT_PROGRAM__CONSTRAINTS = eINSTANCE.getConstraintProgram_Constraints();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.VariablesImpl <em>Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.VariablesImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getVariables()
     * @generated
     */
    EClass VARIABLES = eINSTANCE.getVariables();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLES__NAME = eINSTANCE.getVariables_Name();

    /**
     * The meta object literal for the '<em><b>Dom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLES__DOM = eINSTANCE.getVariables_Dom();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.DomImpl <em>Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.DomImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getDom()
     * @generated
     */
    EClass DOM = eINSTANCE.getDom();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.RangeDomImpl <em>Range Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.RangeDomImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getRangeDom()
     * @generated
     */
    EClass RANGE_DOM = eINSTANCE.getRangeDom();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE_DOM__START = eINSTANCE.getRangeDom_Start();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE_DOM__END = eINSTANCE.getRangeDom_End();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.SetDomImpl <em>Set Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.SetDomImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getSetDom()
     * @generated
     */
    EClass SET_DOM = eINSTANCE.getSetDom();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SET_DOM__LIST = eINSTANCE.getSetDom_List();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.BoolDomImpl <em>Bool Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.BoolDomImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getBoolDom()
     * @generated
     */
    EClass BOOL_DOM = eINSTANCE.getBoolDom();

    /**
     * The meta object literal for the '<em><b>Dom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_DOM__DOM = eINSTANCE.getBoolDom_Dom();

    /**
     * The meta object literal for the '{@link org.xtext.hlcl.impl.StringDomImpl <em>String Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.hlcl.impl.StringDomImpl
     * @see org.xtext.hlcl.impl.HlclPackageImpl#getStringDom()
     * @generated
     */
    EClass STRING_DOM = eINSTANCE.getStringDom();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_DOM__LIST = eINSTANCE.getStringDom_List();

  }

} //HlclPackage
