/*
 * generated by Xtext 2.13.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HlclStandaloneSetup extends HlclStandaloneSetupGenerated {

	def static void doSetup() {
		new HlclStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
