/*
 * generated by Xtext 2.13.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.HlclRuntimeModule
import org.xtext.HlclStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class HlclIdeSetup extends HlclStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new HlclRuntimeModule, new HlclIdeModule))
	}
	
}
