/*
 * generated by Xtext 2.13.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.hlcl.ui.internal.HlclActivator;

public class HlclUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HlclActivator.getInstance().getInjector("org.xtext.Hlcl");
	}

}
