/*
 * generated by Xtext 2.13.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.hlcl.ui.internal.HlclActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HlclExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HlclActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HlclActivator activator = HlclActivator.getInstance();
		return activator != null ? activator.getInjector(HlclActivator.ORG_XTEXT_HLCL) : null;
	}

}
